// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr2MkUhmLeTJv-fXgvbGAax4JRnSElAq0',
    appId: '1:40155483321:android:c7faec3d18092af9a95f68',
    messagingSenderId: '40155483321',
    projectId: 'agape-89d91',
    storageBucket: 'agape-89d91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb0YPsvl-InhKWH7wq7mew1_iQOVZLiDk',
    appId: '1:40155483321:ios:2d690d61b2ffe184a95f68',
    messagingSenderId: '40155483321',
    projectId: 'agape-89d91',
    storageBucket: 'agape-89d91.firebasestorage.app',
    iosBundleId: 'com.camden.agape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb0YPsvl-InhKWH7wq7mew1_iQOVZLiDk',
    appId: '1:40155483321:ios:e53d842a5230e3bca95f68',
    messagingSenderId: '40155483321',
    projectId: 'agape-89d91',
    storageBucket: 'agape-89d91.firebasestorage.app',
    iosBundleId: 'com.example.agape',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxqNiLtWwpdhvL8A3xtW_uBWiQQ4w-udc',
    appId: '1:40155483321:web:6d2dacde1c3efaeba95f68',
    messagingSenderId: '40155483321',
    projectId: 'agape-89d91',
    authDomain: 'agape-89d91.firebaseapp.com',
    storageBucket: 'agape-89d91.firebasestorage.app',
  );
}
